

class AzkabanError(Exception):
    pass


class ArgumentError(AzkabanError):
    pass
